openapi: 3.0.3
info:
  title: OpenAPI schema for template webservice
components:
  schemas:
    variables:
      required:
      - values
      type: object
      properties:
        values:
          title: Values
          type: object
          description: Helm chart values
          x-walrus-ui:
            group: Basic
            widget: YamlEditor
          default:
            architecture: standalone
            clusterDomain: cluster.local
            diagnosticMode:
              args:
                - infinity
              command:
                - sleep
              enabled: false
            image:
              debug: false
              digest: ''
              pullPolicy: IfNotPresent
              pullSecrets: []
              registry: docker.io
              repository: bitnami/mysql
              tag: 8.0.36-debian-11-r4
            primary:
              containerPorts:
                mysql: 3306
                      
            
        